services:
  pg01:
    image: postgres:13
    container_name: pg01
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - data01:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres
  pmanager:
    image: pmanager:latest
    container_name: pmanager
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg01:5432/postgres
    volumes:
      - app01:/application/index
    ports:
      - 8080:8080
    networks:
      - postgres
volumes:
  data01:
    driver: local
  app01:
    driver: local

networks:
  postgres:
    driver: bridge
